Repository dawn-plex/translate, pull requests merged in 2018-10, with the labels that each got.

#31 添加原文
  articles/A-tour-of-JavaScript-timers-on-the-web.md
Labels: 提交原文

#32 Translation/a tour of java script timers on the web
  articles/A-tour-of-JavaScript-timers-on-the-web.md
Labels: 正在校对, 翻译完成

#38 Translation/structuring projects and naming components in react
  articles/Structuring-projects-and-naming-components-in-react.md
Labels: 前端, 校对待认领
